// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller_Run

#ifndef _PASTEURIZER_CHILLER_RUN_UI_H
#define _PASTEURIZER_CHILLER_RUN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_PasteurizerChiller.h"
#include "ui_PasteurizerChillerAuto.h"
#include "ui_PasteurizerChillerLog.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_418309003);    // assets/Puppy-Hoisting.png
LV_IMG_DECLARE(ui_img_1324469499);    // assets/Face-Plate.png
LV_IMG_DECLARE(ui_img_chilling_png);    // assets/Chilling.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
