// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void event_DisableSOLOEnabled(lv_event_t * e);
void event_DisableSOLODisabled(lv_event_t * e);
void event_CoolCycleSOLOEnabled(lv_event_t * e);
void event_CoolCycleSOLODisabled(lv_event_t * e);
void event_OperationButtonEnabled(lv_event_t * e);
void event_OperationButtonDisabled(lv_event_t * e);
void event_WallHeaterEnabled(lv_event_t * e);
void event_WallHeaterDisabled(lv_event_t * e);
void event_PumpButtonEnabled(lv_event_t * e);
void event_PumpButtonDisabled(lv_event_t * e);
void event_ChillerButtonEnabled(lv_event_t * e);
void event_ChillerButtonDisabled(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
