// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller_Run

#ifndef UI_PASTEURIZERCHILLERLOG_H
#define UI_PASTEURIZERCHILLERLOG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PasteurizerChillerLog
extern void ui_PasteurizerChillerLog_screen_init(void);
extern void ui_PasteurizerChillerLog_screen_destroy(void);
extern lv_obj_t * ui_PasteurizerChillerLog;
extern lv_obj_t * ui_chartLog;
extern lv_obj_t * ui_chartLog_Xaxis;
extern lv_obj_t * ui_chartLog_Yaxis1;
extern lv_obj_t * ui_chartLog_Yaxis2;
extern lv_obj_t * ui_dropdownMode;
extern lv_obj_t * ui_labelTemp;
extern lv_obj_t * ui_labelTime;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PasteurizerChillerLog;
extern lv_obj_t * uic_chartLog;
extern lv_obj_t * uic_dropdownMode;
extern lv_obj_t * uic_labelTemp;
extern lv_obj_t * uic_labelTime;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

