// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller_Run

#include "ui.h"

lv_obj_t * uic_buttonStop;
lv_obj_t * uic_spinboxFlood;
lv_obj_t * uic_spinboxProbe;
lv_obj_t * uic_PasteurizerChillerAuto;
lv_obj_t * ui_PasteurizerChillerAuto = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_Chart1_Xaxis = NULL;
lv_obj_t * ui_Chart1_Yaxis1 = NULL;
lv_obj_t * ui_Chart1_Yaxis2 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_spinboxProbe = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_spinboxFlood = NULL;
lv_obj_t * ui_buttonStop = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_spinboxTime = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
// event funtions

// build funtions

void ui_PasteurizerChillerAuto_screen_init(void)
{
    ui_PasteurizerChillerAuto = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PasteurizerChillerAuto, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_Chart1, 380);
    lv_obj_set_height(ui_Chart1, 324);
    lv_obj_set_x(ui_Chart1, -88);
    lv_obj_set_y(ui_Chart1, -19);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_obj_set_style_bg_image_src(ui_Chart1, &ui_img_chilling_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1_Xaxis = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart1_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart1_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart1_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart1_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart1_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Xaxis, 2 >= 1 ? 2 : 1);
    ui_Chart1_Yaxis1 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart1_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart1,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart1_Yaxis2 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart1_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_series_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart1, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_TabView1 = lv_tabview_create(ui_PasteurizerChillerAuto);
    lv_tabview_set_tab_bar_size(ui_TabView1, 50);
    lv_obj_set_width(ui_TabView1, 100);
    lv_obj_set_height(ui_TabView1, 200);
    lv_obj_set_x(ui_TabView1, 620);
    lv_obj_set_y(ui_TabView1, 120);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 292);
    lv_obj_set_y(ui_Switch1, -142);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -211);
    lv_obj_set_y(ui_Label4, 209);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Probe");

    ui_Label3 = lv_label_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 290);
    lv_obj_set_y(ui_Label3, -173);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Pause");

    ui_spinboxProbe = lv_spinbox_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_spinboxProbe, 70);
    lv_obj_set_height(ui_spinboxProbe, 42);
    lv_obj_set_x(ui_spinboxProbe, -140);
    lv_obj_set_y(ui_spinboxProbe, 209);
    lv_obj_set_align(ui_spinboxProbe, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_spinboxProbe, 4, 2);
    lv_spinbox_set_range(ui_spinboxProbe, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_spinboxProbe, 1 - 1);

    ui_Label5 = lv_label_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -44);
    lv_obj_set_y(ui_Label5, 209);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Flood");

    ui_spinboxFlood = lv_spinbox_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_spinboxFlood, 70);
    lv_obj_set_height(ui_spinboxFlood, 42);
    lv_obj_set_x(ui_spinboxFlood, 26);
    lv_obj_set_y(ui_spinboxFlood, 210);
    lv_obj_set_align(ui_spinboxFlood, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_spinboxFlood, 4, 2);
    lv_spinbox_set_range(ui_spinboxFlood, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_spinboxFlood, 1 - 1);

    ui_buttonStop = lv_switch_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_buttonStop, 50);
    lv_obj_set_height(ui_buttonStop, 25);
    lv_obj_set_x(ui_buttonStop, 292);
    lv_obj_set_y(ui_buttonStop, -51);
    lv_obj_set_align(ui_buttonStop, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 290);
    lv_obj_set_y(ui_Label7, -82);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Stop");

    ui_Label8 = lv_label_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 116);
    lv_obj_set_y(ui_Label8, 208);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Time");

    ui_spinboxTime = lv_spinbox_create(ui_PasteurizerChillerAuto);
    lv_obj_set_width(ui_spinboxTime, 70);
    lv_obj_set_height(ui_spinboxTime, 42);
    lv_obj_set_x(ui_spinboxTime, 186);
    lv_obj_set_y(ui_spinboxTime, 211);
    lv_obj_set_align(ui_spinboxTime, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_spinboxTime, 4, 2);
    lv_spinbox_set_range(ui_spinboxTime, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_spinboxTime, 1 - 1);

    ui_Dropdown1 = lv_dropdown_create(ui_PasteurizerChillerAuto);
    lv_dropdown_set_options(ui_Dropdown1, "Manual\nAuto\nLog");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 305);
    lv_obj_set_y(ui_Dropdown1, 122);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    uic_PasteurizerChillerAuto = ui_PasteurizerChillerAuto;
    uic_spinboxProbe = ui_spinboxProbe;
    uic_spinboxFlood = ui_spinboxFlood;
    uic_buttonStop = ui_buttonStop;

}

void ui_PasteurizerChillerAuto_screen_destroy(void)
{
    if(ui_PasteurizerChillerAuto) lv_obj_del(ui_PasteurizerChillerAuto);

    // NULL screen variables
    uic_PasteurizerChillerAuto = NULL;
    ui_PasteurizerChillerAuto = NULL;
    ui_Chart1 = NULL;
    ui_TabView1 = NULL;
    ui_Switch1 = NULL;
    ui_Label4 = NULL;
    ui_Label3 = NULL;
    uic_spinboxProbe = NULL;
    ui_spinboxProbe = NULL;
    ui_Label5 = NULL;
    uic_spinboxFlood = NULL;
    ui_spinboxFlood = NULL;
    uic_buttonStop = NULL;
    ui_buttonStop = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_spinboxTime = NULL;
    ui_Dropdown1 = NULL;

}
