// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller_Run

#include "ui.h"

lv_obj_t * uic_labelCycle;
lv_obj_t * uic_switchCycle;
lv_obj_t * uic_probeTemp;
lv_obj_t * uic_floodTemp;
lv_obj_t * uic_labelFloodTemp;
lv_obj_t * uic_labelProbeTemp;
lv_obj_t * uic_labelRecirculate;
lv_obj_t * uic_labelHeat;
lv_obj_t * uic_labelWater;
lv_obj_t * uic_labelFlood;
lv_obj_t * uic_labelGlycolChill;
lv_obj_t * uic_ChillerButton;
lv_obj_t * uic_switchPump;
lv_obj_t * uic_WallHeater;
lv_obj_t * uic_switchOperation;
lv_obj_t * uic_CoolSOLO;
lv_obj_t * uic_PasteurizerChiller;
lv_obj_t * ui_PasteurizerChiller = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_CoolSOLO = NULL;
lv_obj_t * ui_switchOperation = NULL;
lv_obj_t * ui_WallHeater = NULL;
lv_obj_t * ui_switchPump = NULL;
lv_obj_t * ui_ChillerButton = NULL;
lv_obj_t * ui_labelGlycolChill = NULL;
lv_obj_t * ui_labelFlood = NULL;
lv_obj_t * ui_labelWater = NULL;
lv_obj_t * ui_labelHeat = NULL;
lv_obj_t * ui_labelRecirculate = NULL;
lv_obj_t * ui_labelProbeTemp = NULL;
lv_obj_t * ui_labelFloodTemp = NULL;
lv_obj_t * ui_floodTemp = NULL;
lv_obj_t * ui_probeTemp = NULL;
lv_obj_t * ui_switchCycle = NULL;
lv_obj_t * ui_labelCycle = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions
void ui_event_CoolSOLO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_CoolCycleSOLOEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_CoolCycleSOLODisabled(e);
    }
}

void ui_event_switchOperation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_OperationButtonEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_OperationButtonDisabled(e);
    }
}

void ui_event_WallHeater(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_WallHeaterEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_WallHeaterDisabled(e);
    }
}

void ui_event_switchPump(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_PumpButtonEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_PumpButtonDisabled(e);
    }
}

void ui_event_ChillerButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_ChillerButtonEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_ChillerButtonDisabled(e);
    }
}

void ui_event_switchCycle(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_CycleButtonEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_CycleButtonDisabled(e);
    }
}

// build funtions

void ui_PasteurizerChiller_screen_init(void)
{
    ui_PasteurizerChiller = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PasteurizerChiller, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PasteurizerChiller, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PasteurizerChiller, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PasteurizerChiller, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PasteurizerChiller, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_PasteurizerChiller);
    lv_image_set_src(ui_Image1, &ui_img_418309003);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 700
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 657
    lv_obj_set_x(ui_Image1, 141);
    lv_obj_set_y(ui_Image1, 8);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CoolSOLO = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_CoolSOLO, 50);
    lv_obj_set_height(ui_CoolSOLO, 25);
    lv_obj_set_x(ui_CoolSOLO, -345);
    lv_obj_set_y(ui_CoolSOLO, 62);
    lv_obj_set_align(ui_CoolSOLO, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_CoolSOLO, 5);
    ui_object_set_themeable_style_property(ui_CoolSOLO, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_CoolSOLO, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_switchOperation = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_switchOperation, 50);
    lv_obj_set_height(ui_switchOperation, 25);
    lv_obj_set_x(ui_switchOperation, -345);
    lv_obj_set_y(ui_switchOperation, -106);
    lv_obj_set_align(ui_switchOperation, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_switchOperation, 5);
    ui_object_set_themeable_style_property(ui_switchOperation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_switchOperation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_WallHeater = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_WallHeater, 50);
    lv_obj_set_height(ui_WallHeater, 25);
    lv_obj_set_x(ui_WallHeater, -345);
    lv_obj_set_y(ui_WallHeater, 0);
    lv_obj_set_align(ui_WallHeater, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_WallHeater, 5);
    ui_object_set_themeable_style_property(ui_WallHeater, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_WallHeater, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_switchPump = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_switchPump, 50);
    lv_obj_set_height(ui_switchPump, 25);
    lv_obj_set_x(ui_switchPump, -345);
    lv_obj_set_y(ui_switchPump, -54);
    lv_obj_set_align(ui_switchPump, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_switchPump, 5);
    ui_object_set_themeable_style_property(ui_switchPump, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_switchPump, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_ChillerButton = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_ChillerButton, 50);
    lv_obj_set_height(ui_ChillerButton, 25);
    lv_obj_set_x(ui_ChillerButton, -345);
    lv_obj_set_y(ui_ChillerButton, 116);
    lv_obj_set_align(ui_ChillerButton, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_ChillerButton, 5);
    ui_object_set_themeable_style_property(ui_ChillerButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_ChillerButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_labelGlycolChill = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelGlycolChill, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelGlycolChill, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelGlycolChill, -236);
    lv_obj_set_y(ui_labelGlycolChill, 116);
    lv_obj_set_align(ui_labelGlycolChill, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelGlycolChill, "Glycol Chill");
    lv_obj_set_style_text_font(ui_labelGlycolChill, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFlood = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelFlood, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFlood, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFlood, -275);
    lv_obj_set_y(ui_labelFlood, -107);
    lv_obj_set_align(ui_labelFlood, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFlood, "Flood");
    lv_obj_set_style_text_font(ui_labelFlood, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelWater = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelWater, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelWater, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelWater, -231);
    lv_obj_set_y(ui_labelWater, 62);
    lv_obj_set_align(ui_labelWater, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelWater, "Fresh Water");
    lv_obj_set_style_text_font(ui_labelWater, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelHeat = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelHeat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelHeat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelHeat, -274);
    lv_obj_set_y(ui_labelHeat, 0);
    lv_obj_set_align(ui_labelHeat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelHeat, "Heat");
    lv_obj_set_style_text_font(ui_labelHeat, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelRecirculate = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelRecirculate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelRecirculate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelRecirculate, -240);
    lv_obj_set_y(ui_labelRecirculate, -56);
    lv_obj_set_align(ui_labelRecirculate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelRecirculate, "Recirculate");
    lv_obj_set_style_text_font(ui_labelRecirculate, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelProbeTemp = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelProbeTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelProbeTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelProbeTemp, -64);
    lv_obj_set_y(ui_labelProbeTemp, -131);
    lv_obj_set_align(ui_labelProbeTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelProbeTemp, "Probe Temp");
    lv_obj_set_style_text_font(ui_labelProbeTemp, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFloodTemp = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelFloodTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFloodTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFloodTemp, -62);
    lv_obj_set_y(ui_labelFloodTemp, -206);
    lv_obj_set_align(ui_labelFloodTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFloodTemp, "Flood Temp");
    lv_obj_set_style_text_font(ui_labelFloodTemp, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_floodTemp = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_floodTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_floodTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_floodTemp, -63);
    lv_obj_set_y(ui_floodTemp, -167);
    lv_obj_set_align(ui_floodTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_floodTemp, "Temp in C");
    lv_obj_set_style_text_color(ui_floodTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_floodTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_floodTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_floodTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_floodTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_pad_left(ui_floodTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_floodTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_floodTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_floodTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_probeTemp = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_probeTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_probeTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_probeTemp, -62);
    lv_obj_set_y(ui_probeTemp, -100);
    lv_obj_set_align(ui_probeTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_probeTemp, "Temp in C");
    lv_obj_set_style_text_color(ui_probeTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_probeTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_probeTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_probeTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_probeTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_probeTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_pad_left(ui_probeTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_probeTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_probeTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_probeTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switchCycle = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_switchCycle, 50);
    lv_obj_set_height(ui_switchCycle, 25);
    lv_obj_set_x(ui_switchCycle, -343);
    lv_obj_set_y(ui_switchCycle, 186);
    lv_obj_set_align(ui_switchCycle, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_switchCycle, 5);
    lv_obj_set_style_bg_color(ui_switchCycle, lv_color_hex(0x00CEBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switchCycle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelCycle = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelCycle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelCycle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelCycle, -218);
    lv_obj_set_y(ui_labelCycle, 188);
    lv_obj_set_align(ui_labelCycle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelCycle, "Run \nPasteurization\nCycle");
    lv_obj_set_style_text_font(ui_labelCycle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_PasteurizerChiller);
    lv_image_set_src(ui_Image2, &ui_img_1324469499);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_Image2, 365);
    lv_obj_set_y(ui_Image2, 210);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_CoolSOLO, ui_event_CoolSOLO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchOperation, ui_event_switchOperation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WallHeater, ui_event_WallHeater, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchPump, ui_event_switchPump, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ChillerButton, ui_event_ChillerButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchCycle, ui_event_switchCycle, LV_EVENT_ALL, NULL);
    uic_PasteurizerChiller = ui_PasteurizerChiller;
    uic_CoolSOLO = ui_CoolSOLO;
    uic_switchOperation = ui_switchOperation;
    uic_WallHeater = ui_WallHeater;
    uic_switchPump = ui_switchPump;
    uic_ChillerButton = ui_ChillerButton;
    uic_labelGlycolChill = ui_labelGlycolChill;
    uic_labelFlood = ui_labelFlood;
    uic_labelWater = ui_labelWater;
    uic_labelHeat = ui_labelHeat;
    uic_labelRecirculate = ui_labelRecirculate;
    uic_labelProbeTemp = ui_labelProbeTemp;
    uic_labelFloodTemp = ui_labelFloodTemp;
    uic_floodTemp = ui_floodTemp;
    uic_probeTemp = ui_probeTemp;
    uic_switchCycle = ui_switchCycle;
    uic_labelCycle = ui_labelCycle;

}

void ui_PasteurizerChiller_screen_destroy(void)
{
    if(ui_PasteurizerChiller) lv_obj_del(ui_PasteurizerChiller);

    // NULL screen variables
    uic_PasteurizerChiller = NULL;
    ui_PasteurizerChiller = NULL;
    ui_Image1 = NULL;
    uic_CoolSOLO = NULL;
    ui_CoolSOLO = NULL;
    uic_switchOperation = NULL;
    ui_switchOperation = NULL;
    uic_WallHeater = NULL;
    ui_WallHeater = NULL;
    uic_switchPump = NULL;
    ui_switchPump = NULL;
    uic_ChillerButton = NULL;
    ui_ChillerButton = NULL;
    uic_labelGlycolChill = NULL;
    ui_labelGlycolChill = NULL;
    uic_labelFlood = NULL;
    ui_labelFlood = NULL;
    uic_labelWater = NULL;
    ui_labelWater = NULL;
    uic_labelHeat = NULL;
    ui_labelHeat = NULL;
    uic_labelRecirculate = NULL;
    ui_labelRecirculate = NULL;
    uic_labelProbeTemp = NULL;
    ui_labelProbeTemp = NULL;
    uic_labelFloodTemp = NULL;
    ui_labelFloodTemp = NULL;
    uic_floodTemp = NULL;
    ui_floodTemp = NULL;
    uic_probeTemp = NULL;
    ui_probeTemp = NULL;
    uic_switchCycle = NULL;
    ui_switchCycle = NULL;
    uic_labelCycle = NULL;
    ui_labelCycle = NULL;
    ui_Image2 = NULL;

}
