// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller_Run

#ifndef UI_PASTEURIZERCHILLER_H
#define UI_PASTEURIZERCHILLER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PasteurizerChiller
extern void ui_PasteurizerChiller_screen_init(void);
extern void ui_PasteurizerChiller_screen_destroy(void);
extern lv_obj_t * ui_PasteurizerChiller;
extern lv_obj_t * ui_Image1;
extern void ui_event_CoolSOLO(lv_event_t * e);
extern lv_obj_t * ui_CoolSOLO;
extern void ui_event_switchOperation(lv_event_t * e);
extern lv_obj_t * ui_switchOperation;
extern void ui_event_WallHeater(lv_event_t * e);
extern lv_obj_t * ui_WallHeater;
extern void ui_event_switchPump(lv_event_t * e);
extern lv_obj_t * ui_switchPump;
extern void ui_event_ChillerButton(lv_event_t * e);
extern lv_obj_t * ui_ChillerButton;
extern lv_obj_t * ui_labelGlycolChill;
extern lv_obj_t * ui_labelFlood;
extern lv_obj_t * ui_labelWater;
extern lv_obj_t * ui_labelHeat;
extern lv_obj_t * ui_labelRecirculate;
extern lv_obj_t * ui_labelProbeTemp;
extern lv_obj_t * ui_labelFloodTemp;
extern lv_obj_t * ui_floodTemp;
extern lv_obj_t * ui_probeTemp;
extern void ui_event_switchCycle(lv_event_t * e);
extern lv_obj_t * ui_switchCycle;
extern lv_obj_t * ui_labelCycle;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PasteurizerChiller;
extern lv_obj_t * uic_CoolSOLO;
extern lv_obj_t * uic_switchOperation;
extern lv_obj_t * uic_WallHeater;
extern lv_obj_t * uic_switchPump;
extern lv_obj_t * uic_ChillerButton;
extern lv_obj_t * uic_labelGlycolChill;
extern lv_obj_t * uic_labelFlood;
extern lv_obj_t * uic_labelWater;
extern lv_obj_t * uic_labelHeat;
extern lv_obj_t * uic_labelRecirculate;
extern lv_obj_t * uic_labelProbeTemp;
extern lv_obj_t * uic_labelFloodTemp;
extern lv_obj_t * uic_floodTemp;
extern lv_obj_t * uic_probeTemp;
extern lv_obj_t * uic_switchCycle;
extern lv_obj_t * uic_labelCycle;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

