// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller

#include "ui.h"

lv_obj_t * uic_probeTemp;
lv_obj_t * uic_chamberTemp;
lv_obj_t * uic_labelFloodTemp;
lv_obj_t * uic_labelProbeTemp;
lv_obj_t * uic_labelRecirculate;
lv_obj_t * uic_labelHeat;
lv_obj_t * uic_labelPasteurize;
lv_obj_t * uic_labelWater;
lv_obj_t * uic_labelFlood;
lv_obj_t * uic_labelGlycolChill;
lv_obj_t * uic_ChillerButton;
lv_obj_t * uic_switchPump;
lv_obj_t * uic_labelWallHeater;
lv_obj_t * uic_WallHeater;
lv_obj_t * uic_labelOperation;
lv_obj_t * uic_switchOperation;
lv_obj_t * uic_labelCoolCycleSOLO;
lv_obj_t * uic_CoolSOLO;
lv_obj_t * uic_labelDisableSolo;
lv_obj_t * uic_DisableSOLO;
lv_obj_t * uic_PasteurizerChiller;
lv_obj_t * ui_PasteurizerChiller = NULL;
lv_obj_t * ui_DisableSOLO = NULL;
lv_obj_t * ui_labelDisableSolo = NULL;
lv_obj_t * ui_CoolSOLO = NULL;
lv_obj_t * ui_labelCoolCycleSOLO = NULL;
lv_obj_t * ui_switchOperation = NULL;
lv_obj_t * ui_labelOperation = NULL;
lv_obj_t * ui_WallHeater = NULL;
lv_obj_t * ui_labelWallHeater = NULL;
lv_obj_t * ui_switchPump = NULL;
lv_obj_t * ui_ChillerButton = NULL;
lv_obj_t * ui_labelGlycolChill = NULL;
lv_obj_t * ui_labelFlood = NULL;
lv_obj_t * ui_labelWater = NULL;
lv_obj_t * ui_labelPasteurize = NULL;
lv_obj_t * ui_labelHeat = NULL;
lv_obj_t * ui_labelRecirculate = NULL;
lv_obj_t * ui_labelProbeTemp = NULL;
lv_obj_t * ui_labelFloodTemp = NULL;
lv_obj_t * ui_chamberTemp = NULL;
lv_obj_t * ui_probeTemp = NULL;
// event funtions
void ui_event_DisableSOLO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_DisableSOLOEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_DisableSOLODisabled(e);
    }
}

void ui_event_CoolSOLO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_CoolCycleSOLOEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_CoolCycleSOLODisabled(e);
    }
}

void ui_event_switchOperation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_OperationButtonEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_OperationButtonDisabled(e);
    }
}

void ui_event_WallHeater(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_WallHeaterEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_WallHeaterDisabled(e);
    }
}

void ui_event_switchPump(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_PumpButtonEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_PumpButtonDisabled(e);
    }
}

void ui_event_ChillerButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_ChillerButtonEnabled(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        event_ChillerButtonDisabled(e);
    }
}

// build funtions

void ui_PasteurizerChiller_screen_init(void)
{
    ui_PasteurizerChiller = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PasteurizerChiller, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DisableSOLO = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_DisableSOLO, 50);
    lv_obj_set_height(ui_DisableSOLO, 25);
    lv_obj_set_x(ui_DisableSOLO, -166);
    lv_obj_set_y(ui_DisableSOLO, -85);
    lv_obj_set_align(ui_DisableSOLO, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_DisableSOLO, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_DisableSOLO, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_labelDisableSolo = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelDisableSolo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelDisableSolo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelDisableSolo, -149);
    lv_obj_set_y(ui_labelDisableSolo, -115);
    lv_obj_set_align(ui_labelDisableSolo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelDisableSolo, "Disable SOLO");

    ui_CoolSOLO = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_CoolSOLO, 50);
    lv_obj_set_height(ui_CoolSOLO, 25);
    lv_obj_set_x(ui_CoolSOLO, 36);
    lv_obj_set_y(ui_CoolSOLO, -80);
    lv_obj_set_align(ui_CoolSOLO, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_CoolSOLO, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_CoolSOLO, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_labelCoolCycleSOLO = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelCoolCycleSOLO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelCoolCycleSOLO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelCoolCycleSOLO, 45);
    lv_obj_set_y(ui_labelCoolCycleSOLO, -113);
    lv_obj_set_align(ui_labelCoolCycleSOLO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelCoolCycleSOLO, "Cool Cycle SOLO");

    ui_switchOperation = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_switchOperation, 50);
    lv_obj_set_height(ui_switchOperation, 25);
    lv_obj_set_x(ui_switchOperation, 197);
    lv_obj_set_y(ui_switchOperation, -78);
    lv_obj_set_align(ui_switchOperation, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_switchOperation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_switchOperation, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_labelOperation = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelOperation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelOperation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelOperation, 199);
    lv_obj_set_y(ui_labelOperation, -112);
    lv_obj_set_align(ui_labelOperation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelOperation, "Operation");

    ui_WallHeater = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_WallHeater, 50);
    lv_obj_set_height(ui_WallHeater, 25);
    lv_obj_set_x(ui_WallHeater, -172);
    lv_obj_set_y(ui_WallHeater, 26);
    lv_obj_set_align(ui_WallHeater, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_WallHeater, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_WallHeater, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_labelWallHeater = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelWallHeater, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelWallHeater, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelWallHeater, -165);
    lv_obj_set_y(ui_labelWallHeater, -7);
    lv_obj_set_align(ui_labelWallHeater, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelWallHeater, "Wall Heater");

    ui_switchPump = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_switchPump, 50);
    lv_obj_set_height(ui_switchPump, 25);
    lv_obj_set_x(ui_switchPump, 29);
    lv_obj_set_y(ui_switchPump, 31);
    lv_obj_set_align(ui_switchPump, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_switchPump, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_switchPump, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_ChillerButton = lv_switch_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_ChillerButton, 50);
    lv_obj_set_height(ui_ChillerButton, 25);
    lv_obj_set_x(ui_ChillerButton, 192);
    lv_obj_set_y(ui_ChillerButton, 27);
    lv_obj_set_align(ui_ChillerButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_ChillerButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Orange);
    ui_object_set_themeable_style_property(ui_ChillerButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Orange);

    ui_labelGlycolChill = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelGlycolChill, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelGlycolChill, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelGlycolChill, 198);
    lv_obj_set_y(ui_labelGlycolChill, -24);
    lv_obj_set_align(ui_labelGlycolChill, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelGlycolChill, "Glycol Chill");
    lv_obj_set_style_text_font(ui_labelGlycolChill, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFlood = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelFlood, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFlood, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFlood, 191);
    lv_obj_set_y(ui_labelFlood, -140);
    lv_obj_set_align(ui_labelFlood, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFlood, "Flood");
    lv_obj_set_style_text_font(ui_labelFlood, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelWater = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelWater, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelWater, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelWater, 35);
    lv_obj_set_y(ui_labelWater, -146);
    lv_obj_set_align(ui_labelWater, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelWater, "Fresh Water");
    lv_obj_set_style_text_font(ui_labelWater, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPasteurize = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelPasteurize, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPasteurize, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPasteurize, -165);
    lv_obj_set_y(ui_labelPasteurize, -151);
    lv_obj_set_align(ui_labelPasteurize, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPasteurize, "Run Pasteurization\nCycle");
    lv_obj_set_style_text_font(ui_labelPasteurize, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelHeat = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelHeat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelHeat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelHeat, -166);
    lv_obj_set_y(ui_labelHeat, -34);
    lv_obj_set_align(ui_labelHeat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelHeat, "Heater");
    lv_obj_set_style_text_font(ui_labelHeat, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelRecirculate = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelRecirculate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelRecirculate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelRecirculate, 42);
    lv_obj_set_y(ui_labelRecirculate, -20);
    lv_obj_set_align(ui_labelRecirculate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelRecirculate, "Recirculating\nPump");
    lv_obj_set_style_text_font(ui_labelRecirculate, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelProbeTemp = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelProbeTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelProbeTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelProbeTemp, -173);
    lv_obj_set_y(ui_labelProbeTemp, 138);
    lv_obj_set_align(ui_labelProbeTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelProbeTemp, "Probe Temp");
    lv_obj_set_style_text_font(ui_labelProbeTemp, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFloodTemp = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_labelFloodTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFloodTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFloodTemp, 93);
    lv_obj_set_y(ui_labelFloodTemp, 138);
    lv_obj_set_align(ui_labelFloodTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFloodTemp, "Flood Temp");
    lv_obj_set_style_text_font(ui_labelFloodTemp, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chamberTemp = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_chamberTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chamberTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chamberTemp, 79);
    lv_obj_set_y(ui_chamberTemp, 176);
    lv_obj_set_align(ui_chamberTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chamberTemp, "Temp in C");

    ui_probeTemp = lv_label_create(ui_PasteurizerChiller);
    lv_obj_set_width(ui_probeTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_probeTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_probeTemp, -176);
    lv_obj_set_y(ui_probeTemp, 174);
    lv_obj_set_align(ui_probeTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_probeTemp, "Temp in C");

    lv_obj_add_event_cb(ui_DisableSOLO, ui_event_DisableSOLO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CoolSOLO, ui_event_CoolSOLO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchOperation, ui_event_switchOperation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WallHeater, ui_event_WallHeater, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchPump, ui_event_switchPump, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ChillerButton, ui_event_ChillerButton, LV_EVENT_ALL, NULL);
    uic_PasteurizerChiller = ui_PasteurizerChiller;
    uic_DisableSOLO = ui_DisableSOLO;
    uic_labelDisableSolo = ui_labelDisableSolo;
    uic_CoolSOLO = ui_CoolSOLO;
    uic_labelCoolCycleSOLO = ui_labelCoolCycleSOLO;
    uic_switchOperation = ui_switchOperation;
    uic_labelOperation = ui_labelOperation;
    uic_WallHeater = ui_WallHeater;
    uic_labelWallHeater = ui_labelWallHeater;
    uic_switchPump = ui_switchPump;
    uic_ChillerButton = ui_ChillerButton;
    uic_labelGlycolChill = ui_labelGlycolChill;
    uic_labelFlood = ui_labelFlood;
    uic_labelWater = ui_labelWater;
    uic_labelPasteurize = ui_labelPasteurize;
    uic_labelHeat = ui_labelHeat;
    uic_labelRecirculate = ui_labelRecirculate;
    uic_labelProbeTemp = ui_labelProbeTemp;
    uic_labelFloodTemp = ui_labelFloodTemp;
    uic_chamberTemp = ui_chamberTemp;
    uic_probeTemp = ui_probeTemp;

}

void ui_PasteurizerChiller_screen_destroy(void)
{
    if(ui_PasteurizerChiller) lv_obj_del(ui_PasteurizerChiller);

    // NULL screen variables
    uic_PasteurizerChiller = NULL;
    ui_PasteurizerChiller = NULL;
    uic_DisableSOLO = NULL;
    ui_DisableSOLO = NULL;
    uic_labelDisableSolo = NULL;
    ui_labelDisableSolo = NULL;
    uic_CoolSOLO = NULL;
    ui_CoolSOLO = NULL;
    uic_labelCoolCycleSOLO = NULL;
    ui_labelCoolCycleSOLO = NULL;
    uic_switchOperation = NULL;
    ui_switchOperation = NULL;
    uic_labelOperation = NULL;
    ui_labelOperation = NULL;
    uic_WallHeater = NULL;
    ui_WallHeater = NULL;
    uic_labelWallHeater = NULL;
    ui_labelWallHeater = NULL;
    uic_switchPump = NULL;
    ui_switchPump = NULL;
    uic_ChillerButton = NULL;
    ui_ChillerButton = NULL;
    uic_labelGlycolChill = NULL;
    ui_labelGlycolChill = NULL;
    uic_labelFlood = NULL;
    ui_labelFlood = NULL;
    uic_labelWater = NULL;
    ui_labelWater = NULL;
    uic_labelPasteurize = NULL;
    ui_labelPasteurize = NULL;
    uic_labelHeat = NULL;
    ui_labelHeat = NULL;
    uic_labelRecirculate = NULL;
    ui_labelRecirculate = NULL;
    uic_labelProbeTemp = NULL;
    ui_labelProbeTemp = NULL;
    uic_labelFloodTemp = NULL;
    ui_labelFloodTemp = NULL;
    uic_chamberTemp = NULL;
    ui_chamberTemp = NULL;
    uic_probeTemp = NULL;
    ui_probeTemp = NULL;

}
