// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller_Run

#include "ui.h"

lv_obj_t * uic_labelTime;
lv_obj_t * uic_labelTemp;
lv_obj_t * uic_dropdownMode;
lv_obj_t * uic_chartLog;
lv_obj_t * uic_PasteurizerChillerLog;
lv_obj_t * ui_PasteurizerChillerLog = NULL;
lv_obj_t * ui_chartLog = NULL;
lv_obj_t * ui_chartLog_Xaxis = NULL;
lv_obj_t * ui_chartLog_Yaxis1 = NULL;
lv_obj_t * ui_chartLog_Yaxis2 = NULL;
lv_obj_t * ui_dropdownMode = NULL;
lv_obj_t * ui_labelTemp = NULL;
lv_obj_t * ui_labelTime = NULL;
// event funtions

// build funtions

void ui_PasteurizerChillerLog_screen_init(void)
{
    ui_PasteurizerChillerLog = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PasteurizerChillerLog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chartLog = lv_chart_create(ui_PasteurizerChillerLog);
    lv_obj_set_width(ui_chartLog, 587);
    lv_obj_set_height(ui_chartLog, 232);
    lv_obj_set_x(ui_chartLog, 13);
    lv_obj_set_y(ui_chartLog, -10);
    lv_obj_set_align(ui_chartLog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_chartLog, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_chartLog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_chartLog, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_chartLog, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_chartLog, LV_CHART_TYPE_LINE);

    ui_chartLog_Xaxis = lv_scale_create(ui_chartLog);
    lv_scale_set_mode(ui_chartLog_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_chartLog_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_chartLog_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_chartLog_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_chartLog,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_chartLog, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_chartLog_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartLog_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_chartLog_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartLog_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_chartLog_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_chartLog_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_chartLog_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_chartLog_Xaxis, 2 >= 1 ? 2 : 1);
    ui_chartLog_Yaxis1 = lv_scale_create(ui_chartLog);
    lv_scale_set_mode(ui_chartLog_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_chartLog_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_chartLog_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_chartLog_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_chartLog,
                                                                     LV_PART_MAIN) - lv_obj_get_style_border_width(ui_chartLog, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_chartLog_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartLog_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chartLog_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartLog_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chartLog_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_chartLog_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_chartLog_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_chartLog_Yaxis2 = lv_scale_create(ui_chartLog);
    lv_scale_set_mode(ui_chartLog_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_chartLog_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_chartLog_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_chartLog_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_chartLog,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_chartLog, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_chartLog_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_chartLog_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_chartLog_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_chartLog_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_chartLog_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_chartLog_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_chartLog_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_chartLog_series_1 = lv_chart_add_series(ui_chartLog, lv_color_hex(0x808080),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_chartLog_series_1_array[] = { 0, 10, 20, 40, 72, 72, 40, 20, 10, 0 };
    lv_chart_set_series_ext_y_array(ui_chartLog, ui_chartLog_series_1, ui_chartLog_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_chartLog, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_chartLog, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_dropdownMode = lv_dropdown_create(ui_PasteurizerChillerLog);
    lv_dropdown_set_options(ui_dropdownMode, "Auto\nManual\nLog");
    lv_obj_set_width(ui_dropdownMode, 150);
    lv_obj_set_height(ui_dropdownMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dropdownMode, 308);
    lv_obj_set_y(ui_dropdownMode, 206);
    lv_obj_set_align(ui_dropdownMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropdownMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_labelTemp = lv_label_create(ui_PasteurizerChillerLog);
    lv_obj_set_width(ui_labelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTemp, -347);
    lv_obj_set_y(ui_labelTemp, -148);
    lv_obj_set_align(ui_labelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp, "Temp (C)");

    ui_labelTime = lv_label_create(ui_PasteurizerChillerLog);
    lv_obj_set_width(ui_labelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTime, -13);
    lv_obj_set_y(ui_labelTime, 172);
    lv_obj_set_align(ui_labelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTime, "Time (min)");

    uic_PasteurizerChillerLog = ui_PasteurizerChillerLog;
    uic_chartLog = ui_chartLog;
    uic_dropdownMode = ui_dropdownMode;
    uic_labelTemp = ui_labelTemp;
    uic_labelTime = ui_labelTime;

}

void ui_PasteurizerChillerLog_screen_destroy(void)
{
    if(ui_PasteurizerChillerLog) lv_obj_del(ui_PasteurizerChillerLog);

    // NULL screen variables
    uic_PasteurizerChillerLog = NULL;
    ui_PasteurizerChillerLog = NULL;
    uic_chartLog = NULL;
    ui_chartLog = NULL;
    uic_dropdownMode = NULL;
    ui_dropdownMode = NULL;
    uic_labelTemp = NULL;
    ui_labelTemp = NULL;
    uic_labelTime = NULL;
    ui_labelTime = NULL;

}
