// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller_Run

#ifndef UI_PASTEURIZERCHILLERAUTO_H
#define UI_PASTEURIZERCHILLERAUTO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PasteurizerChillerAuto
extern void ui_PasteurizerChillerAuto_screen_init(void);
extern void ui_PasteurizerChillerAuto_screen_destroy(void);
extern lv_obj_t * ui_PasteurizerChillerAuto;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_spinboxProbe;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_spinboxFlood;
extern lv_obj_t * ui_buttonStop;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_spinboxTime;
extern lv_obj_t * ui_Dropdown1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PasteurizerChillerAuto;
extern lv_obj_t * uic_spinboxProbe;
extern lv_obj_t * uic_spinboxFlood;
extern lv_obj_t * uic_buttonStop;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

