// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Orange[1] = {0xF68E40};
const ui_theme_variable_t _ui_theme_alpha_Orange[1] = {255};

const ui_theme_variable_t _ui_theme_color_Blue[1] = {0x6699F3};
const ui_theme_variable_t _ui_theme_alpha_Blue[1] = {255};

const ui_theme_variable_t _ui_theme_color_Yellow[1] = {0xFAC949};
const ui_theme_variable_t _ui_theme_alpha_Yellow[1] = {255};

const ui_theme_variable_t _ui_theme_color_LightBlue[1] = {0x00E9FF};
const ui_theme_variable_t _ui_theme_alpha_LightBlue[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

