// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Pasteurizer_Chiller

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_ORANGE 0
#define UI_THEME_COLOR_BLUE 1
#define UI_THEME_COLOR_YELLOW 2
#define UI_THEME_COLOR_LIGHTBLUE 3

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Orange[1];
extern const ui_theme_variable_t _ui_theme_alpha_Orange[1];

extern const ui_theme_variable_t _ui_theme_color_Blue[1];
extern const ui_theme_variable_t _ui_theme_alpha_Blue[1];

extern const ui_theme_variable_t _ui_theme_color_Yellow[1];
extern const ui_theme_variable_t _ui_theme_alpha_Yellow[1];

extern const ui_theme_variable_t _ui_theme_color_LightBlue[1];
extern const ui_theme_variable_t _ui_theme_alpha_LightBlue[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
